### PR TITLE
Fixes delete p['t']

### LINKED ISSUE #347: Error formatting sentences with delete
Online demo:

http://goo.gl/S9jrSo

Input

```javascript
delete changedFiles[ path ];
```

formatted:

```javascript
delete changedFiles[ path ]
;
```

### PR DESCRIPTION
**Pull request by TommyM**
Closes #347

### CODE REVIEW

File: lib/hooks/UnaryExpression.js [hunk 1]
```diff
@@ -9,7 +9,11 @@ exports.format = function UnaryExpression(node) {
   if (node.operator === 'delete') {
     _ws.limitAfter(node.startToken, 1);
     _br.limitBefore(node.startToken, 'DeleteOperator');
+
     var endToken = node.endToken;
+    if (_tk.isWs(endToken.next)) {
+      _ws.limitAfter(endToken, 0);
```
Comment (TommyM) [inline lib/hooks/UnaryExpression.js]: I tried several approaches to fixing this issue, but all had some side effects.

This solution works for all the following:
```javascript
  delete this['bar']
  delete this['amet'];
  delete this['ipsum'];
```

**Comment by nederdirk** [comment]
:+1:

**Comment by millermedeiros** [comment]
@TommyM thanks for all the fixes! keep them coming!
